version: '3.8'
services:
  db:
    image: mongo:5
    restart: always
    container_name: mongodb
    environment:
      MONGODB_DATABASE: db-pokemon
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data: {}