services:
  db:
    image: mongo:latest
    container_name: mongo-short-url
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: y0urP422w0rDH3r3
      MONGO_INITDB_DATABASE: short-url
    volumes:
      - ./mongo-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    name: short-url-mongo-data