services:
  db:
    image: mongo:5
    container_name: mongo-short-url
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: short-url
    volumes:
      - ./mongo:/data/db